# Codecov configuration
coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 1%
        if_not_found: success
    patch:
      default:
        target: 80%
        threshold: 5%
        if_not_found: success

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true

ignore:
  - "tests/"
  - "example_project/"
  - "setup.py"
  - "docs/"
  - "*.md"
